# Generated by Django 4.1.7 on 2023-12-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_events_uploaded_alter_events_name_alter_events_reg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='uploaded',
            new_name='upt',
        ),
    ]
