# Generated by Django 4.1.7 on 2023-12-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_uploaded_events_upt'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='location',
            field=models.CharField(default='lemari abu', max_length=20),
        ),
    ]
